config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/odnoruchnyj-topor', to: 'static_pages#one_hand_axe', via: 'get'
  match '/kogti', to: 'static_pages#kogti', via: 'get'
  match '/odnoruchnyj-kinzhal', to: 'static_pages#kinzhal', via: 'get'
  match '/odnoruchnaya-bulava', to: 'static_pages#1h-mace', via: 'get'
  match '/skipetr', to: 'static_pages#skipetr', via: 'get'
  match '/odnoruchnyj-mech', to: 'static_pages#one_hand_sword', via: 'get'
  match '/zhezl', to: 'static_pages#zhezl', via: 'get'
  match '/dvuruchnyj-topor', to: 'static_pages#two_hand_axe', via: 'get'
  match '/luk', to: 'static_pages#bow', via: 'get'
  match '/dvuruchnaya-bulava', to: 'static_pages#two_hand_mace', via: 'get'
  match '/posoh', to: 'static_pages#staff', via: 'get'
  match '/dvuruchnyj-mech', to: 'static_pages#two_hand_sword', via: 'get'
  match '/udochka', to: 'static_pages#fishing_rod', via: 'get'
  match '/bronya', to: 'static_pages#body_armour', via: 'get'
  match '/uklonenie', to: 'static_pages#body_evasion', via: 'get'
  match '/ehnergeticheskij-shchit', to: 'static_pages#body_armour_es', via: 'get'
  match '/bronya-ehnergeticheskij-shchit', to: 'static_pages#body_armour_es_bron', via: 'get'
  match '/bronya-uklonenie', to: 'static_pages#body_armour_bron_ev', via: 'get'
  match '/ehnergeticheskij-shchit-uklonenie', to: 'static_pages#body_armour_es_uklonenie', via: 'get'
  match '/zhertvennoe-oblachenie', to: 'static_pages#body_armour_zhertvennoe_oblachenie', via: 'get'
  match '/shlem/bronya', to: 'static_pages#helmet_armour', via: 'get'
  match '/shlem/uklonenie', to: 'static_pages#helmet_evasion', via: 'get'
  match '/shlem/ehnergeticheskij-shchit', to: 'static_pages#helmet_es', via: 'get'
  match '/shlem/bronya-ehnergeticheskij-shchit', to: 'static_pages#helmet_armour_es', via: 'get'
  match '/shlem/bronya-uklonenie', to: 'static_pages#helmet_armour_ev', via: 'get'
  match '/shlem/ehnergeticheskij-shchit-uklonenie', to: 'static_pages#helmet_ev_es', via: 'get'
  match '/perchatki/bronya', to: 'static_pages#gloves_armour', via: 'get'
  match '/perchatki/uklonenie', to: 'static_pages#gloves_evasion', via: 'get'
  match '/perchatki/ehnergeticheskij-shchit', to: 'static_pages#gloves_es', via: 'get'
  match '/perchatki/bronya-uklonenie', to: 'static_pages#gloves_armour_ev', via: 'get'
  match '/perchatki/bronya-ehnergeticheskij-shchit', to: 'static_pages#gloves_armour_es', via: 'get'
  match '/perchatki/ehnergeticheskij-shchit-uklonenie', to: 'static_pages#gloves_ev_es', via: 'get'
end

app/models/gloves.rb
class Gloves
  attr_accessor :armour, :evasion, :es, :armour_es, :armour_ev, :ev_es

  TO_MAX_LIFE = { red: "#f00", green: "#f1f1", blue: "#f00", white: "#fff" }

  # def initialize(options = {}) # options = хэш аргументов
  #   @armour = options[:armour]
  #   # @model = options[:model] || "Unknown" #к хэшу по названию или присваем Unknown
  #   # @number_of_wagons = options[:number_of_wagons] || "0" #Обращаемся по индексу или присваем 0
  # end

  # def initialize
  #   @armour = to_max_life
  # end

  def initialize
   @armour = '<p>to_max_life</p>'
   gloves = Gloves.new
  end

  def code
    @to_maximum_life = TO_MAX_LIFE[:blue]
  end

  def show
    'to max'
  end
  #gloves.code(:blue)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Возвращает полный заголовок зависящий от страницы # Документирующий комментарий
  def full_title(page_title)                          # Определение метода
    base_title = "Префиксы и Суффиксы PoE"  # Назначение переменной
    if page_title.empty?                              # Булевый тест
      base_title                                      # Явное возвращение
    else
      "#{page_title} | #{base_title}"                 # Интерполяция строки
    end
  end

  # Попытки создать хэлпер 
  def full_meta_description(page_description)
    base_description = "Помощь в крафте предметов в игре Path of Exile - Список Префиксов и Суффиксов на все предметы"
    if page_description.empty?
      base_description
    else
      "#{page_description}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">#</a>
    #
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Навигация</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <li><%= link_to "Главная",    root_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Одноручное<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/odnoruchnyj-topor">Топор</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Когти",    kogti_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Кинжал",    '/odnoruchnyj-kinzhal' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Булава",    '/odnoruchnaya-bulava' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Скипетр",    '/skipetr' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Меч",    '/odnoruchnyj-mech' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Жезл",    '/zhezl' %></li>
          </ul>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Двуручное<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Топор",    '/dvuruchnyj-topor' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Лук",    '/luk' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Булава",    '/dvuruchnaya-bulava' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Посох",    '/posoh' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Меч",    '/dvuruchnyj-mech' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Удочка",    '/udochka' %></li>
          </ul>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Нагрудные доспехи<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Броня",    '/bronya' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Уклонение",    '/uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Энергетический щит",    '/ehnergeticheskij-shchit' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Броня / Энергетический щит",    '/bronya-ehnergeticheskij-shchit' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Броня / Уклонение",    '/bronya-uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Энергетический Щит / Уклонение",    '/ehnergeticheskij-shchit-uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Жертвенное облачение",    '/zhertvennoe-oblachenie' %></li>
          </ul>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Шлем<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Броня",    '/shlem/bronya' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Уклонение",    '/shlem/uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Энергетический щит",    '/shlem/ehnergeticheskij-shchit' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Броня / Энергетический щит",    '/shlem/bronya-ehnergeticheskij-shchit' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Броня / Уклонение",    '/shlem/bronya-uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Энергетический щит / Уклонение",    '/shlem/ehnergeticheskij-shchit-uklonenie' %></li>
          </ul>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Перчатки<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Броня",    '/perchatki/bronya' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Уклонение",    '/perchatki/uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Энергетический щит",    '/perchatki/ehnergeticheskij-shchit' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Броня / Энергетический щит",    '/perchatki/bronya-ehnergeticheskij-shchit' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Броня / Уклонение",    '/perchatki/bronya-uklonenie' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Энергетический Щит / Уклонение",    '/perchatki/ehnergeticheskij-shchit-uklonenie' %></li>
          </ul>
          <li><%= link_to "Помощь",    help_path %></li>
        </li>
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= full_meta_description(yield(:description)) %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="/imgaes/favicon-16x16.png" sizes="16x16" />
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
Пусто.

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
В данный момент пусто.

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>


<ul class='divination'>
<li>I’m writing a long list item 1 so you can see what happens when the text wraps across multiple lines</li>
<li>List item 2</li>
<li>List item 3</li>
</ul>

app/views/static_pages/home.html.erb
<% provide(:title, 'Главная страница') %>
<% provide(:description, 'Помощь в крафте предметов в игре Path of Exile - Список Префиксов и Суффиксов на все предметы.') %>
<div class="center hero-unit">
  <h1><center>Префиксы и Суффиксы PoE</center></h1>

  <h2>Полный кликабельный список предметов:</h2>

 <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/one-hand.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Одноручное оружие</h4>
    	<ol class="breadcrumb">
		  <li><a href="/odnoruchnyj-topor">Топор</a></li>
		  <li><a href="/kogti">Когти</a></li>
		  <li><a href="/odnoruchnyj-kinzhal">Кинжал</a></li>
		  <li><a href="/odnoruchnaya-bulava">Булава</a></li>
		  <li><a href="/skipetr">Скипетр</a></li>
		  <li><a href="/odnoruchnyj-mech">Меч</a></li>
		  <li><a href="/zhezl">Жезл</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/two-hand.jpg" alt="Одноручное оружие Path of Exile">
 </div>
  <div class="media-body">
    <h4 class="media-heading">Двуручное оружие</h4>
    	<ol class="breadcrumb">
		  <li><a href="/dvuruchnyj-topor">Топор</a></li>
		  <li><a href="/luk">Лук</a></li>
		  <li><a href="/dvuruchnaya-bulava">Булава</a></li>
		  <li><a href="/posoh">Посох</a></li>
		  <li><a href="/dvuruchnyj-mech">Меч</a></li>
		  <li><a href="/udochka">Удочка</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/body-armour.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Нагрудный доспех</h4>
    	<ol class="breadcrumb">
		  <li><a href="/bronya">Броня</a></li>
		  <li><a href="/uklonenie">Уклонение</a></li>
		  <li><a href="/ehnergeticheskij-shchit">Энергетический Щит</a></li>
		  <li><a href="/bronya-ehnergeticheskij-shchit">Броня | Энергетический Щит</a></li>
		  <li><a href="/bronya-uklonenie">Броня | Уклонение</a></li>
		  <li><a href="/ehnergeticheskij-shchit-uklonenie">Уклонение | Энергетический Щит</a></li>
		  <li><a href="/zhertvennoe-oblachenie">Жертвенное облачение</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/helmet.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Шлем</h4>
    	<ol class="breadcrumb">
		  <li><a href="/shlem/bronya">Броня</a></li>
		  <li><a href="/shlem/uklonenie">Уклонение</a></li>
		  <li><a href="/shlem/ehnergeticheskij-shchit">Энергетический Щит</a></li>
		  <li><a href="/shlem/bronya-ehnergeticheskij-shchit">Броня | Энергетический Щит</a></li>
		  <li><a href="/shlem/bronya-uklonenie">Броня | Уклонение</a></li>
		  <li><a href="/shlem/ehnergeticheskij-shchit-uklonenie">Уклонение | Энергетический Щит</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/gloves.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Перчатки</h4>
    	<ol class="breadcrumb">
		  <li><a href="/perchatki/bronya">Броня</a></li>
      <li><a href="/perchatki/uklonenie">Уклонение</a></li>
      <li><a href="/perchatki/ehnergeticheskij-shchit">Энергетический Щит</a></li>
      <li><a href="/perchatki/bronya-ehnergeticheskij-shchit">Броня | Энергетический Щит</a></li>
      <li><a href="/perchatki/bronya-uklonenie">Броня | Уклонение</a></li>
      <li><a href="/perchatki/ehnergeticheskij-shchit-uklonenie">Уклонение | Энергетический Щит</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/boots.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Обувь</h4>
    	<ol class="breadcrumb">
		  <li><a href="#">Броня</a></li>
		  <li><a href="#">Уклонение</a></li>
		  <li><a href="#">Энергетический Щит</a></li>
		  <li><a href="#">Броня | Энергетический Щит</a></li>
		  <li><a href="#">Броня | Уклонение</a></li>
		  <li><a href="#">Уклонение | Энергетический Щит</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/shield.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Щит</h4>
    	<ol class="breadcrumb">
		  <li><a href="#">Броня</a></li>
		  <li><a href="#">Уклонение</a></li>
		  <li><a href="#">Энергетический Щит</a></li>
		  <li><a href="#">Броня | Энергетический Щит</a></li>
		  <li><a href="#">Броня | Уклонение</a></li>
		  <li><a href="#">Уклонение | Энергетический Щит</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/jewel.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Самоцвет</h4>
    	<ol class="breadcrumb">
		  <li><a href="#">Кобальтовый самоцвет</a></li>
		  <li><a href="#">Багровый самоцвет</a></li>
		  <li><a href="#">Бирюзовый самоцвет</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->
  <div class="media">
  <div class="media-left media-middle">
      <img class="media-object" src="/images/accessories.jpg" alt="Одноручное оружие Path of Exile">
  </div>
  <div class="media-body">
    <h4 class="media-heading">Аксессуары</h4>
    	<ol class="breadcrumb">
		  <li><a href="#">Талисманы</a></li>
		  <li><a href="#">Пояса</a></li>
		  <li><a href="#">Кольца</a></li>
		  <li><a href="#">Колчаны</a></li>
		</ol>
  </div>
</div>
<!-- end of div -->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>